### PR TITLE
AOS-304 Ensure that birth dates cannot be after today

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Review by Edzelopez — COMMENTED** [review]
I'm wasn't certain this was actually required, since CiviCRM uses a different date picker to build birth date which restricts one to select a future date. I then manually entered in a future date and I was able to save the contact. This patch does make sense to validate all forms with the birth_date field. Approving it.

**Comment by JoeMurray** [comment]
Sorry, this seems the opposite of what I would expect. Where is documentation of requirement? Future dates for birth dates would mean one was guessing about when a baby would be born This field is normally understood to refer to a contact's birth date, and a contact would be born already. Or is it for when a contact is expected to give birth??

**Comment by seamuslee001** [comment]
@JoeMurray that is precisely what this is doing it is stopping someone from entering a date of birth beyond today, According to the ticket you were able to set say a date of birth of tomorrow when filling in the form

**Comment by JoeMurray** [comment]
Agree totally after looking at code. I've changed the PR title that confused me.

**Pull request merged**
