### PR TITLE
AOS-478 Re-format price field amounts for french display

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@Edzelopez just noting this is currently deployed on staging

**Review by Edzelopez — DISMISSED** [review]
Labels look fine on staging.

**Review by Edzelopez — CHANGES_REQUESTED** [review]
Confirmation page and thank you page will require the same labels in french

**Comment by seamuslee001** [comment]
@Edzelopez I believe I have solved the issue on the Confirm and Thank you step can you please re-check

**Comment by Edzelopez** [comment]
Changes look good.

**Pull request merged**
